### ISSUE TITLE
Contribute an FTPDownloader back to Pooch

### ISSUE THREAD

**Issue by leouieda** [NCAR/aletheia-data#4]
Hi @andersy005 I'm really glad that Pooch was useful for you! This is an interesting project and FTP access is a really useful thing. Would you consider contributing an `FTPDownloader` back to Pooch so that more people can benefit? Thanks!

**Comment by andersy005** [comment]
@leouieda,

> Would you consider contributing an FTPDownloader back to Pooch so that more people can benefit? Thanks!

Definitely! I am on it (I will submit a PR very soon)
